// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upkmsdsxfandyhlkrdes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwa21zZHN4ZmFuZHlobGtyZGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTkyNTgsImV4cCI6MjA3MzA5NTI1OH0.Su7oEC5RWho7QCNxBDGJ7ibRGSu_oUuBFmR-g_V4WtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});